### ISSUE TITLE
Fresh Install Missing Pages Collection

### ISSUE THREAD

**Issue by devingray** [spatie/statamic-blade-starter-kit#2]
When using statamic CLI and choosing `spatie/statamic-blade-starter-kit` as the starter kit, all works well but the pages collection is no longer configured, loading {domain}.test in the browser shows 404 page

**Comment by devingray** [comment]
Closing due to non activity :)

**Comment by riasvdv** [comment]
Was on holiday, I’d like to add this so reopening

**Comment by Codex101** [comment]
Copy the same collections/blueprint structure as the default fresh install and the home page will show up as per normal. No clue how to do this in code though? 

That's what I did.

**Comment by devingray** [comment]
@riasvdv I have edited this to work in statamic in my own project, I also added a cool bard blade component that nests sub components to display bard sets. Would you be interested? Or do you want to fo it

**Comment by riasvdv** [comment]
Feel free to PR things! I'll review and change things as needed.
