### ISSUE TITLE
SSL certificate problem with CLI install

### ISSUE THREAD

**Issue by stuartcusackie** [spatie/statamic-blade-starter-kit#4]
Hey, nice idea. Booo antlers.

I just tried this command today:
`statamic new mysite spatie/statamic-blade-starter-kit`

but I hit an SSL certificate problem 
`cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://repo.packagist.org/p2/spatie/statamic-blade-starter-kit.json`

Using the CLI without the starter kit works fine for me. Windows 10 in case it's related to that.

**Comment by riasvdv** [comment]
This is not an issue with the starter kit itself.

A google search on the error brings me this https://laracasts.com/discuss/channels/general-discussion/curl-error-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate which might be of help
